site_name: Blue Frontline Docs

nav:
  - Ustilisateur: index.md
  - Admin: MANUEL_ADMINISTRATEUR.md
  - API: api.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths : 
            - ../blue_frontline
