site_name: Blue Frontline Docs

nav:
  - Utilisateur: doc_user.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ../blue_frontline
  - redirects:
      redirect_maps:
        'index.md': 'doc_user.md'

# Ces fichiers ne sont pas dans la navigation,
# mais restent construits et accessibles via leur URL directe.
extra:
  include_hidden: true

markdown_extensions:
  - toc:
      permalink: true

docs_dir: docs
