from .paths import GREEN_TEAM_PATH_BIG, RED_TEAM_PATH_BIG

UNIT_CONFIGS = {
    "chaloupe": {
        "cost": 20,
        "max_speed": 80,
        "max_health": 20,
        "range": 2,
        "damage": 2,
        "fire_rate": 1.0,
        "unit_type": "chaloupe",
        "tile_index": {"red": 0, "green": 0},
        "tileset_paths": {"red": RED_TEAM_PATH_BIG, "green": GREEN_TEAM_PATH_BIG},
        "range_color": {"red": (255, 0, 0, 50), "green": (0, 255, 0, 50)},
    },
    "bateau": {
        "cost": 60,
        "max_speed": 70,
        "max_health": 30,
        "range": 6,
        "damage": 6,
        "fire_rate": 1.0,
        "unit_type": "bateau",
        "tile_index": {"red": 1, "green": 1},
        "tileset_paths": {"red": RED_TEAM_PATH_BIG, "green": GREEN_TEAM_PATH_BIG},
        "range_color": {"red": (255, 0, 0, 50), "green": (0, 255, 0, 50)},
    },
    "eclaireur": {
        "cost": 40,
        "max_speed": 100,
        "max_health": 15,
        "range": 0,
        "damage": 0,
        "fire_rate": 0,
        "unit_type": "eclaireur",
        "tile_index": {"red": 3, "green": 3},
        "tileset_paths": {"red": RED_TEAM_PATH_BIG, "green": GREEN_TEAM_PATH_BIG},
        "range_color": {"red": (255, 0, 0, 50), "green": (0, 255, 0, 50)},
    },
    "paquebot": {
        "cost": 120,
        "max_speed": 60,
        "max_health": 50,
        "range": 8,
        "damage": 10,
        "fire_rate": 0.8,
        "unit_type": "paquebot",
        "tile_index": {"red": 2, "green": 2},
        "tileset_paths": {"red": RED_TEAM_PATH_BIG, "green": GREEN_TEAM_PATH_BIG},
        "range_color": {"red": (255, 0, 0, 50), "green": (0, 255, 0, 50)},
    },
    "sousmarin": {
        "cost": 180,
        "max_speed": 65,
        "max_health": 35,
        "range": 0,
        "damage": 12,
        "fire_rate": 1,
        "unit_type": "sousmarin",
        "special_ability": "mines",
        "tile_index": {"red": 4, "green": 4},
        "tileset_paths": {"red": RED_TEAM_PATH_BIG, "green": GREEN_TEAM_PATH_BIG},
        "range_color": {"red": (255, 0, 0, 50), "green": (0, 255, 0, 50)},
    },
    "pompe_petroliere": {
        "cost": 500,
        "max_speed": 0,
        "max_health": 100,
        "range": 0,
        "damage": 0,
        "fire_rate": 1,
        "unit_type": "pompe_petroliere",
        "tile_index": {"red": 6, "green": 6},
        "tileset_paths": {"red": RED_TEAM_PATH_BIG, "green": GREEN_TEAM_PATH_BIG},
        "range_color": {"red": (255, 0, 0, 50), "green": (0, 255, 0, 50)},
    },
}
